adminUser:
  password: vault:pr-418-1arc/adminUser:password
  username: admin
dashboardAuthID: vault:pr-418-1arc:dashboardAuthID
dashboardAuthOrg: arcalos-dashboard
dashboardAuthSecret: vault:pr-418-1arc:dashboardAuthSecret
dashboardGrpchost: dex.jx
enableDocker: false
pipelineUser:
  email: arcalos-admin@googlegroups.com
  token: vault:pr-418-1arc/pipelineUser:token
  username: arcalos-bot
prow:
  hmacToken: vault:pr-418-1arc/prow:hmacToken
